### ISSUE TITLE
Extension crashes with DGS

### ISSUE THREAD

**Issue by wesranch** [LANDIS-II-Foundation/Extension-Output-Biomass-Community#13]
This is the error I get when running this extension with DGS

Running Output Biomass Community ...
Internal error occurred within the program:
  Field not found: 'Landis.Library.UniversalCohorts.CohortData.ANPP'.
![Community_Error](https://github.com/user-attachments/assets/41f11438-0703-492c-86a1-90fcd2c1183b)

**Comment by rmscheller** [comment]
Wesley, I can't speak for DGS, but it is now running correctly with Biomass and NECN succession.  New installer posted.

**Comment by wesranch** [comment]
Thank you Rob!
