### ISSUE TITLE
Communities not output

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Output-Biomass-Community#2]
I started with this as a single cell and the attached file is the output from time step =0. So it should have a map code 3 in the attached file.
MapCode 3 <<this is my new IC community
QuakingAspen 10 (42) 20 (130)

Also, I thought the plan was to spit out a txt file more like a spreadsheet that would make it easier to read into R. Like column for map code, one for species, one for age, one for biomass. Too hard to code?

**Comment by rmscheller** [comment]
No.  One of the goals is to reproduce the inputs.  This extension needs to serve multiple purposes, including allowing short runs that generate inputs.

**Comment by rmscheller** [comment]
I fixed the numbering problem.  New installer.

**Comment by mslucash** [comment]
The output looks great.  I think it should create a txt file not a csv file to avoid confusion about the output.

**Comment by rmscheller** [comment]
Ah, yes, good point.  I will change that.

**Comment by rmscheller** [comment]
Done.
