### ISSUE TITLE
No maps are generated.

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-Output-Biomass-Community#3]
It doesn't make any maps.  
It's not obvious to me from the InputParm files how to get it to generate the maps based on key words in the input file.   Or is it just the default and it's not working?

**Comment by rmscheller** [comment]
It's just not working.

**Comment by rmscheller** [comment]
Fixed.

**Comment by rmscheller** [comment]
I assume this has been resolved.
