### ISSUE TITLE
specific output files you would prefer?

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-Output-Biomass-Community#8]
It would be great if you could specify which output file you want . Writing the txt file slows down the run (more so than the csv file) and I never need it. But others might want the txt file and not the csv file. Why not an input parameter that says "csv" or "txt" or "both"?

**Comment by rmscheller** [comment]
Core v8 initial communities no longer supports the txt option and so I'm closing this issue.
